"""Added Student model

Revision ID: 8bcaf3ebfe57
Revises: 83de240a4ed5
Create Date: 2024-03-19 08:41:12.808351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bcaf3ebfe57'
down_revision = '83de240a4ed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
